title: iavivai.com
url: https://iavivai.com
image: /images/iavivai.jpeg
logo: /images/iavivai.jpeg
syntax_highlighter: rouge
lang: ja_JP

twitter:
  username: yukitakaiha
  card: summary_large_image

plugins:
  - jekyll-seo-tag

google_analytics: UA-146131644-2

defaults:
- scope:
    path: ''
  values:
    image: "/images/iavivai.jpeg"
