title: utakaha.com
description: "utakaha's personal site"
url: https://utakaha.com
image: /images/utakaha.jpeg
logo: /images/utakaha.jpeg
syntax_highlighter: rouge
lang: ja_JP

twitter:
  username: utakaha
  card: summary_large_image

plugins:
  - jekyll-seo-tag

google_analytics: UA-146131644-2

defaults:
- scope:
    path: ''
  values:
    image: "/images/utakaha.jpeg"
